# Generated by Django 2.1.1 on 2018-09-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20180922_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='spots_available',
            field=models.IntegerField(default=5),
        ),
    ]
