# Generated by Django 2.1.1 on 2018-10-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_team_spots_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='budget_available',
            field=models.FloatField(default=100.0, editable=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='spots_available',
            field=models.IntegerField(default=5, editable=False),
        ),
    ]
