# Generated by Django 2.1.1 on 2018-10-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20181023_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='captain',
        ),
    ]
